name: Post welcome comment
on:
  pull_request:
    types:
      [opened]
permissions:
  pull-requests: write

jobs:
  welcome:
    name: Dis bonjour
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment "$PR_URL" --body "Bienvenu dans le repo !"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
